# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b44819bef39d27d1d0d5c0829b148f6d6106c317176c1075069b58e8ac207a2836c7b485cac335611613866774be5a99947b065282385ae49c95cf54e84256

test:
  secret_key_base: 5d59a3cc248ec03e7f801865735ff3e080b323270f626511544cf1badb43620529071ff2ae6e18e1f412fbcce0ac2ba07814140caa438e7a2c0455175a772305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
